In [1]:
import pandas as pd

fish = pd.read_csv("fish.csv")
fish

length  weight  class
0     25.4   242.0      1
1     26.3   290.0      1
2     26.5   340.0      1
3     29.0   363.0      1
4     29.0   430.0      1
5     29.7   450.0      1
6     29.7   500.0      1
7     30.0   390.0      1
8     30.0   450.0      1
9     30.7   500.0      1
10    31.0   475.0      1
11    31.0   500.0      1
12    31.5   500.0      1
13    32.0   340.0      1
14    32.0   600.0      1
15    32.0   600.0      1
16    33.0   700.0      1
17    33.0   700.0      1
18    33.5   610.0      1
19    33.5   650.0      1
20    34.0   575.0      1
21    34.0   685.0      1
22    34.5   620.0      1
23    35.0   680.0      1
24    35.0   700.0      1
25    35.0   725.0      1
26    35.0   720.0      1
27    36.0   714.0      1
28    36.0   850.0      1
29    37.0  1000.0      1
30    38.5   920.0      1
31    38.5   955.0      1
32    39.5   925.0      1
33    41.0   975.0      1
34    41.0   950.0      1
35     9.8     6.7      0
36    10.5     7.5      0
37    10.6     7.0      0
38    11.0     9.7      0
39    11.2     9.8      0
40    11.3     8.7      0
41    11.8    10.0      0
42    11.8     9.9      0
43    12.0     9.8      0
44    12.2    12.2      0
45    12.4    13.4      0
46    13.0    12.2      0
47    14.3    19.7      0
48    15.0    19.9      0

In [5]:
data = fish[['length', 'weight']].to_numpy()
data

array([[  25.4,  242. ],
       [  26.3,  290. ],
       [  26.5,  340. ],
       [  29. ,  363. ],
       [  29. ,  430. ],
       [  29.7,  450. ],
       [  29.7,  500. ],
       [  30. ,  390. ],
       [  30. ,  450. ],
       [  30.7,  500. ],
       [  31. ,  475. ],
       [  31. ,  500. ],
       [  31.5,  500. ],
       [  32. ,  340. ],
       [  32. ,  600. ],
       [  32. ,  600. ],
       [  33. ,  700. ],
       [  33. ,  700. ],
       [  33.5,  610. ],
       [  33.5,  650. ],
       [  34. ,  575. ],
       [  34. ,  685. ],
       [  34.5,  620. ],
       [  35. ,  680. ],
       [  35. ,  700. ],
       [  35. ,  725. ],
       [  35. ,  720. ],
       [  36. ,  714. ],
       [  36. ,  850. ],
       [  37. , 1000. ],
       [  38.5,  920. ],
       [  38.5,  955. ],
       [  39.5,  925. ],
       [  41. ,  975. ],
       [  41. ,  950. ],
       [   9.8,    6.7],
       [  10.5,    7.5],
       [  10.6,    7. ],
       [  11. ,    9.7],
       [  11.2,    9.8],


In [7]:
target = fish['class'].to_numpy()
target

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0])

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

train_input, test_input, train_target, test_target = train_test_split(data, target) # 기본값은 75 // 훈련세트 : 25 // 시험세트
knn = KNeighborsClassifier()
knn.fit(train_input, train_target)

KNeighborsClassifier()

In [15]:
knn.score(test_input, test_target)

1.0

In [16]:
test_target # 실제값

array([1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0])

In [17]:
knn.predict(test_input) # 예상값

array([1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0])