In [3]:
import pandas as pd

perch = pd.read_csv("perch.csv")
target = perch['weight'].to_numpy()

In [4]:
target

array([   5.9,   32. ,   40. ,   51.5,   70. ,  100. ,   78. ,   80. ,
         85. ,   85. ,  110. ,  115. ,  125. ,  130. ,  120. ,  120. ,
        130. ,  135. ,  110. ,  130. ,  150. ,  145. ,  150. ,  170. ,
        225. ,  145. ,  188. ,  180. ,  197. ,  218. ,  300. ,  260. ,
        265. ,  250. ,  250. ,  300. ,  320. ,  514. ,  556. ,  840. ,
        685. ,  700. ,  700. ,  690. ,  900. ,  650. ,  820. ,  850. ,
        900. , 1015. ,  820. , 1100. , 1000. , 1100. , 1000. , 1000. ])

In [6]:
perch2 = pd.read_csv("perch2.csv").to_numpy()
perch2

array([[ 8.4 ,  2.11,  1.41],
       [13.7 ,  3.53,  2.  ],
       [15.  ,  3.82,  2.43],
       [16.2 ,  4.59,  2.63],
       [17.4 ,  4.59,  2.94],
       [18.  ,  5.22,  3.32],
       [18.7 ,  5.2 ,  3.12],
       [19.  ,  5.64,  3.05],
       [19.6 ,  5.14,  3.04],
       [20.  ,  5.08,  2.77],
       [21.  ,  5.69,  3.56],
       [21.  ,  5.92,  3.31],
       [21.  ,  5.69,  3.67],
       [21.3 ,  6.38,  3.53],
       [22.  ,  6.11,  3.41],
       [22.  ,  5.64,  3.52],
       [22.  ,  6.11,  3.52],
       [22.  ,  5.88,  3.52],
       [22.  ,  5.52,  4.  ],
       [22.5 ,  5.86,  3.62],
       [22.5 ,  6.79,  3.62],
       [22.7 ,  5.95,  3.63],
       [23.  ,  5.22,  3.63],
       [23.5 ,  6.28,  3.72],
       [24.  ,  7.29,  3.72],
       [24.  ,  6.38,  3.82],
       [24.6 ,  6.73,  4.17],
       [25.  ,  6.44,  3.68],
       [25.6 ,  6.56,  4.24],
       [26.5 ,  7.17,  4.14],
       [27.3 ,  8.32,  5.14],
       [27.5 ,  7.17,  4.34],
       [27.5 ,  7.05,  4.34],
       [27

In [11]:
perch2.shape # 56개 데이터와 3개의 특성

(56, 3)

In [29]:
from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(include_bias=False, degree = 5) # 5 제곱까지 허용
perch_poly = poly.fit_transform(perch2)

In [30]:
perch_poly.shape #특성 공학으로 9개의 특성으로 늘려짐 x1 **2, x1 **2, x1 **2, x1 * x2, x2 * x3, x3 * x1 의 데이터 추가

(56, 55)

In [31]:
from sklearn.model_selection import train_test_split

train_input, test_input, train_target, test_target = train_test_split(perch_poly, target)

In [32]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler() # 표준화 라이브러리
train_scaled = ss.fit_transform(train_input) # train_input의 평균, 표준편차를 학습해서 얻고, 변환해서 train_sclaed에 널어라
test_scaled = ss.transform(test_input) # 위에서 구했던 train_input의 편균, 표준편차를 변환해서 test_scaled에 넣어라

In [33]:
import numpy as np
np.std(train_scaled, axis = 0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1.])

In [34]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(train_scaled, train_target)

LinearRegression()

In [35]:
lr.score(test_scaled, test_target)

-64052.42778828179

In [ ]:
# 상기 결과가 나온 이유는 너무 모델이 학습 세트에 맞아버렸기 때문
# 과하게 특성을 늘리는 작업은 오히려 부정확한 결과가 나올 수도 있음